import Head from "next/head";

const Meta = ({ title, keywords, description }) => {
	return (
		<Head>
			<title>Access App</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
	);
};

export default Meta;
